### ISSUE TITLE
Tabs sit "above" and are offset from the tab bar

### ISSUE THREAD

**Issue by chrisdotcode** [Zonnev/elementaryos-firefox-theme#193]
Hello,

I'm grateful that you guys keep updating this as Firefox seems to keep making (unnecessary) UI changes. Recently-ish, they changed something again, and now it seems that tabs hover over the tab bar, image attached. As you can see, the selected (and hovered) tabs are "above" the tab bar itself. My font size is set to 1.25 if it matters, but even when I changed back to 1.0, I still have the same issue.

![image](https://user-images.githubusercontent.com/1936426/214365286-9aefb2c7-1494-4367-bb78-47c577f5dc4f.png)

FF v108.0.2 (64-bit). Happy to provide more info as needed.

Thanks!

**Comment by Zonnev** [comment]
I think I fixed this in latest style sheets, you have to update the theme to put the changes in effect. Updating the theme is discribed in the readme.

**Comment by chrisdotcode** [comment]
Hey @Zonnev, I reinitialized my install with `bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/Zonnev/elementaryos-firefox-theme/elementaryos-firefox-theme/install.sh")` before opening the issue, and also updated with `bash <(wget --quiet --output-document - "https://raw.githubusercontent.com/Zonnev/elementaryos-firefox-theme/elementaryos-firefox-theme/install.sh") --update` to the same (broken) result.

**Comment by chrisdotcode** [comment]
I also just re-downloaded master and ran `install.sh` from https://github.com/Zonnev/elementaryos-firefox-theme/commit/7025a33563f37a467b68c85553a89ac303f3d131, and the issue still persists, sadly.

**Comment by Zonnev** [comment]
I installed Firefox 108.02 and made the style sheets work in that browser. I still can not reproduce your issue, the tabs are inside the tab bar, not like in your screenshot. 

Maybe if you make a new profile in Firefox and put the `chrome` folder with the style sheets in that new profile folder, change `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`, restart the browser, it will maybe work?

**Comment by chrisdotcode** [comment]
You're correct. I spun up a completely new system in a VM, and I didn't have that problem there (even with text size set to 1.25). I suppose something unusual happened within my own system's installation.

Thank you.
