### ISSUE TITLE
Can't move the window on ff 66

### ISSUE THREAD

**Issue by Hedronmx** [Zonnev/elementaryos-firefox-theme#23]
Can't move the window by draggin the top of the window... Not sure if related to chrome style or ff66

**Comment by Zonnev** [comment]
Hm, it's weird. Between the menu icon and window controls you can still drag but not at the top of the url bar anymore... I guess ff66 removed this, I have not specified anything on this matter in the userChrome. The tab bar is kept draggable which is logical since it's on top in the default theme. This makes dragging different than in elementary OS: instead of dragging the top bar (like in Files) you have to drag the tab bar (you can not do that in Files).

If you want to drag everywhere in the window, press the function/windows button on your keyboard and drag.

**Comment by Zonnev** [comment]
I fixed it in the new userChrome. You are now able to drag the window at the top again.

**Comment by sempasha** [comment]
Firefox 70.0.1 issue is back. Can't drag window by space around address bar, only space around close and maximize buttons works.

**Comment by Zonnev** [comment]
@sempasha I've fixed it again. I was aware of it since the Megabar arrived. I had to figure out a solution and found it.
